name: PriceLoreInjector
version: '1.1'
main: me.not_ryuzaki.priceLoreInjector.PriceLoreInjector
api-version: '1.21'
depend: [ProtocolLib, Vault]
commands:
  worth:
    description: Shows the items worth in the chat & action bar.
    usage: /worth

  sell:
    description: Open the selling inventory GUI.
    usage: /sell